### ISSUE TITLE
Support Jira integration

### ISSUE THREAD

**Issue by tomasbjerre** [tomasbjerre/git-changelog-bitbucket-plugin#1]
To get title or issues and link to them

**Comment by hoppfrosch** [comment]
Github support would also by nice within 
- {{commits.message}}
- {{commits.messageTitle}}
- {{commits.messageBody}}
- {{commits.messageBodyItems}}

I use to use JIRA-issue reference (i.E TST-123) within my commit messages. It would be nice if those would be "auto-linkified"

**Comment by tomasbjerre** [comment]
I created another issue for GitHub here: #2
