### ISSUE TITLE
Initial changelog

### ISSUE THREAD

**Issue by hoppfrosch** [tomasbjerre/git-changelog-bitbucket-plugin#14]
This refers to **_plugin version 1.5_**

**Issue:** Opening the ChangeLog page for a repository initially, **the generated changelog is EMPTY** (see attachment) - the "From branch" and "To branch" do not have any default values.
![firefox_2016-02-18_10-27-43](https://cloud.githubusercontent.com/assets/419075/13139069/ed7e6b22-d62a-11e5-8777-71a501e7e242.png)

**Suggestions**
- Provide some default values for "From Branch" and "To Branch" (maybe: "First Commit" to "Default Branch" ("Default Branch" is the default branch for the repository as defined in Bitbucket repository settings
- Maybe you extend the selectable range from "From/To Branch" to "From/To Commit" - doing this you might provide default-values like: "HEAD of Default-Branch" to "last 10 commits" ... (Just an idea ...)
 

**Issue:**
After having selected an "From Branch" and "To Branch" the page refreshes and a Changelog is generated. **Changing the "From/To Branch" again does NOT refresh the changelog** ...

**Suggestion**
- Refresh the changelog on each change of "From/To Branch"

**Comment by tomasbjerre** [comment]
I removed default values on from/to branches to gain performance. But it should definitely be made configurable.

I am testing by importing spring framework repository. I can select from/to branches, see the changelog, select other branches and see the new changelog being generated. Does the Bitbucket Server log say anything? Do you have any special chars in the branch names? If you are using Chrome, does the dev tools console show anything?

**Comment by tomasbjerre** [comment]
Try 1.6, it should refresh correctly now. But still default from/to is not implemented.

**Comment by hoppfrosch** [comment]
Hmmm... just installed 1.7 - Refresh does not work here....

For example I select "From Commit" as "first commit" and "To Commit" as "master" -> Changelog is generated correctly. Now I try to change "From Commit" to a tag from the offered list -> Changelog is NOT refreshed ...

**Comment by tomasbjerre** [comment]
Is the spinner shown? The request may take alot of time if there are many Jiras to lookup, so turning off "lookup jira titles" in admin GUI may help.

**Comment by hoppfrosch** [comment]
Refresh seems to work now
