### ISSUE TITLE
Template: {{hash}} vs. {{hashFull}}

### ISSUE THREAD

**Issue by hoppfrosch** [tomasbjerre/git-changelog-bitbucket-plugin#21]
Within your template (initially provided with your plugin) you use the following: 

`<a href="{{bitbucketUrl}}/bitbucket/projects/{{projectKey}}/repos/{{repositorySlug}}/commits/{{hash}}">{{hash}}</a>`

The **generated link does not work** since bitbucket uses the full hash instead of the shortened one (BTW: even your shortened one is to long in comparison to the hash used in bitbucket: bitbucket use only 6a5ab0e96393 instead of 6a5ab0e96393ca7 you use ...)

I looked in documentation on https://github.com/tomasbjerre/git-changelog-lib and found there a value {{hashFull}} - but this does not work within your modified template:

`<a href="{{bitbucketUrl}}/bitbucket/projects/{{projectKey}}/repos/{{repositorySlug}}/commits/{{hashFull}}">{{hash}}</a>` 

**{{hashFull}} is expanded into an empty string.**

**Comment by hoppfrosch** [comment]
Superb!

**Comment by tomasbjerre** [comment]
Its released in 1.12 now. Open issue again if not working.

**Comment by hoppfrosch** [comment]
Works as expected - see #23. Thanks for the fast fix
