### ISSUE TITLE
JiraClientService uses DisplayUrl instead of RpcUrl

### ISSUE THREAD

**Issue by ljucam** [tomasbjerre/git-changelog-bitbucket-plugin#25]
The `JiraClientService` is using `primaryApplicationLink.getDisplayUrl()` to request the Jira Rest API. This can cause problems if you are behind a proxy. In such an installation, the DisplayUrl is different from the URL being used to create request to the API. To avoid problems with the proxy, it’s better to use `primaryApplicationLink.getRpcUrl()`. This URL is mandatory in the Jira Application Link configuration and is - if no proxy is involved - the same as the DisplayUrl.

**Comment by tomasbjerre** [comment]
PR:s are welcome.

**Comment by ljucam** [comment]
Here we go :)

**Comment by tomasbjerre** [comment]
Great! Will merge and release as soon as possible!

**Comment by tomasbjerre** [comment]
Released now! Thanks.
