### ISSUE TITLE
Hangs for large repos

### ISSUE THREAD

**Issue by hoppfrosch** [tomasbjerre/git-changelog-bitbucket-plugin#6]
The generation of the change log needs a long time if there are lot of commits on the considered branch. During this time, bitbucket server does not respond  - even for other users trying to access other repositories.

The plugin shouldn't tear down the bitbucket server performance as massively as it does now.

Is it possible to introduce a limitiation in changelog entries? Maybe a limitation in the number of commits which occur within the changelog - or a date limit (only use commits after ...) - or another limitation ...

In this context it would be nice if the settings are available per repository (not only globally as it is now ...)

**Comment by tomasbjerre** [comment]
Sounds good, and also #3 will help here.

**Comment by tomasbjerre** [comment]
Just realized that the lib can be greatly improved here:
https://github.com/tomasbjerre/git-changelog-lib/issues/13

**Comment by tomasbjerre** [comment]
How much time are we talking about? How many commits do you have?

**Comment by tomasbjerre** [comment]
I tried with the spring framework, 11000+ commits. It hangs and I get OutOfMemory... I'm not sure such large repos can ever be supported. There are [commandline, jenkins, gradle and maven](https://github.com/tomasbjerre/git-changelog-lib) plugins that are perhaps better suited for those very large repos.

I'm open for a discussion here, any ideas are welcome. I think these featues would be nice.

 * Enable/disable per repository
 * Limit number of commits

**Comment by hoppfrosch** [comment]
Sry for the late answer 
You wrote: _"It hangs and I get OutOfMemory!"_ That's something we experienced too .... We installed your plugin on our production bitbucket and tried it on a huge repository with a long history. As soon as we noticed that it runs very long - and our normal users cannot access to bitbucket anymore - we restarted the server to have it accessible again (so we did no experience the OutOfMemory as we restarted before) 

Your proposed features are the same I thought about ...

Another nice feature would be:
* Generate a changelog starting from tag "XXXX" ...

**Comment by hoppfrosch** [comment]
Concerning proposed fearure: "_Enable/disable per repository_"

On the page with the generated changelog, you already offer a possibility to select a tag, from where the changelog should be generated from. The selected tag should also be stored per repository and should be used as default value on next changelog generation.

**Comment by tomasbjerre** [comment]
I just released 1.2 to Marketplace. It should make a big difference in performance.

I'll try to find some time soon, to fix the other stuff mentioned here.
